import { MediaItem, StreamingProvider } from '@/types/tmdb';

export const STREAMING_PROVIDERS: StreamingProvider[] = [
  {
    id: 'netflix',
    name: 'Netflix',
    logo: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=120&auto=format&fit=crop&q=80',
    color: '#E50914',
    textColor: '#FFFFFF',
    accentBg: '#141414'
  },
  {
    id: 'prime',
    name: 'Amazon Prime Video',
    logo: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=120&auto=format&fit=crop&q=80',
    color: '#00A8E1',
    textColor: '#FFFFFF',
    accentBg: '#0f172a'
  },
  {
    id: 'disney',
    name: 'Disney Plus',
    logo: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=120&auto=format&fit=crop&q=80',
    color: '#113CCF',
    textColor: '#FFFFFF',
    accentBg: '#040714'
  },
  {
    id: 'appletv_plus',
    name: 'Apple TV+',
    logo: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=120&auto=format&fit=crop&q=80',
    color: '#000000',
    textColor: '#FFFFFF',
    accentBg: '#000000'
  },
  {
    id: 'hulu',
    name: 'Hulu',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=120&auto=format&fit=crop&q=80',
    color: '#1CE783',
    textColor: '#0B0C0F',
    accentBg: '#0b0c0f'
  },
  {
    id: 'hbomax',
    name: 'HBO Max',
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=120&auto=format&fit=crop&q=80',
    color: '#7B2CBF',
    textColor: '#FFFFFF',
    accentBg: '#0f051d'
  },
  {
    id: 'paramount',
    name: 'Paramount Plus',
    logo: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=120&auto=format&fit=crop&q=80',
    color: '#0064FF',
    textColor: '#FFFFFF',
    accentBg: '#002244'
  },
  {
    id: 'peacock',
    name: 'Peacock Premium',
    logo: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=120&auto=format&fit=crop&q=80',
    color: '#000000',
    textColor: '#FFFFFF',
    accentBg: '#121212'
  },
  {
    id: 'crunchyroll',
    name: 'Crunchyroll',
    logo: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=120&auto=format&fit=crop&q=80',
    color: '#F47521',
    textColor: '#FFFFFF',
    accentBg: '#23252b'
  },
  {
    id: 'starz',
    name: 'Starz',
    logo: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=120&auto=format&fit=crop&q=80',
    color: '#000000',
    textColor: '#FFFFFF',
    accentBg: '#000000'
  },
  {
    id: 'tubi',
    name: 'Tubi TV',
    logo: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=120&auto=format&fit=crop&q=80',
    color: '#FA5A2A',
    textColor: '#FFFFFF',
    accentBg: '#17181c'
  }
];

export const HERO_FEATURED_ITEMS: MediaItem[] = [
  {
    id: 603,
    title: 'SPIDER-MAN: BRAND NEW DAY',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '2026-07-24',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    overview: 'Peter Parker navigates a fractured universe while forging a clean slate in the heart of Manhattan, facing emerging threats with newfound agility and legendary resolve.',
    backdrop_path: 'https://image.tmdb.org/t/p/w1280/14QbnygCuTO0vl7bY090L7Y33nk.jpg',
    poster_path: 'https://image.tmdb.org/t/p/w342/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    youtube_id: 'JfVOs4VSpmA',
    runtime: 142,
    quality: '4K HDR',
    certification: 'PG-13',
    providers: ['Disney Plus', 'Netflix'],
    cast: [
      { id: 110, name: 'Tom Holland', character: 'Peter Parker / Spider-Man' },
      { id: 111, name: 'Zendaya', character: 'MJ' }
    ]
  },
  {
    id: 1241982,
    title: 'MOANA 2',
    media_type: 'movie',
    vote_average: 7.2,
    release_date: '2024-11-27',
    genres: ['Animation', 'Adventure', 'Family', 'Music'],
    overview: 'After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she’s ever faced.',
    backdrop_path: 'https://image.tmdb.org/t/p/w1280/v9acaWVxduaie2w44q5Ao7r9f4J.jpg',
    poster_path: 'https://image.tmdb.org/t/p/w342/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg',
    youtube_id: 'hDZ7y8RP5HE',
    runtime: 100,
    quality: '4K HDR',
    certification: 'PG',
    providers: ['Disney Plus'],
    cast: [
      { id: 104, name: 'Auliʻi Cravalho', character: 'Moana (voice)' },
      { id: 105, name: 'Dwayne Johnson', character: 'Maui (voice)' }
    ]
  },
  {
    id: 693134,
    title: 'DUNE: PART TWO',
    media_type: 'movie',
    vote_average: 8.3,
    release_date: '2024-03-01',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family, facing a choice between love and the fate of the universe.',
    backdrop_path: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5200fr.jpg',
    poster_path: 'https://image.tmdb.org/t/p/w342/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    youtube_id: 'Way9Dexny3w',
    runtime: 166,
    quality: '4K HDR',
    certification: 'PG-13',
    providers: ['HBO Max'],
    cast: [
      { id: 106, name: 'Timothée Chalamet', character: 'Paul Atreides' },
      { id: 107, name: 'Zendaya', character: 'Chani' }
    ]
  },
  {
    id: 108978,
    title: 'REACHER',
    name: 'REACHER',
    media_type: 'tv',
    vote_average: 8.1,
    first_air_date: '2022-02-04',
    genres: ['Action & Adventure', 'Crime', 'Drama'],
    overview: 'Jack Reacher, a veteran military police investigator, enters civilian life with no phone and the barest of essentials as he travels the country exploring the nation he once served.',
    backdrop_path: 'https://image.tmdb.org/t/p/w1280/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg',
    poster_path: 'https://image.tmdb.org/t/p/w342/j73SrPnljFarECRA2NvaoxBpLVl.jpg',
    youtube_id: 'GSycMV_mptc',
    number_of_seasons: 3,
    quality: '4K HDR',
    certification: 'TV-MA',
    providers: ['Amazon Prime Video']
  },
  {
    id: 872585,
    title: 'OPPENHEIMER',
    media_type: 'movie',
    vote_average: 8.2,
    release_date: '2023-07-21',
    genres: ['Drama', 'History'],
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    backdrop_path: 'https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    poster_path: 'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    youtube_id: 'uYPbbksJxIg',
    runtime: 180,
    quality: '4K HDR',
    certification: 'R',
    providers: ['Peacock', 'Amazon Prime Video']
  }
];

export const TRENDING_MOVIES: MediaItem[] = [
  {
    id: 1241982,
    title: 'Moana 2',
    media_type: 'movie',
    vote_average: 7.2,
    release_date: '2024',
    genres: ['Animation', 'Adventure'],
    overview: 'Moana journeys alongside Maui and a new crew to the far seas of Oceania.',
    poster_path: 'https://image.tmdb.org/t/p/w342/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/v9acaWVxduaie2w44q5Ao7r9f4J.jpg',
    youtube_id: 'hDZ7y8RP5HE',
    quality: '4K HDR',
    providers: ['Disney Plus']
  },
  {
    id: 101,
    title: 'The Odyssey',
    media_type: 'movie',
    vote_average: 8.1,
    release_date: '2025',
    genres: ['Action', 'Adventure', 'Drama'],
    overview: 'An epic adaptation of the ancient journey through mythological realms and heroic battles.',
    poster_path: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'EXeTwQWrcwY',
    quality: '4K HDR',
    providers: ['Amazon Prime Video']
  },
  {
    id: 603,
    title: 'Spider-Man: Brand New Day',
    media_type: 'movie',
    vote_average: 7.8,
    release_date: '2026',
    genres: ['Action', 'Sci-Fi'],
    overview: 'Peter Parker protects the city while balancing his dual identity in an evolving world.',
    poster_path: 'https://image.tmdb.org/t/p/w342/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/14QbnygCuTO0vl7bY090L7Y33nk.jpg',
    youtube_id: 'JfVOs4VSpmA',
    quality: '4K HDR',
    providers: ['Disney Plus', 'Netflix']
  },
  {
    id: 102,
    title: 'Mayday',
    media_type: 'movie',
    vote_average: 7.4,
    release_date: '2025',
    genres: ['Action', 'Thriller'],
    overview: 'A high-stakes tactical mission where survival depends on brotherhood and strategy.',
    poster_path: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1200&auto=format&fit=crop&q=80',
    youtube_id: '4rgYUipGJNo',
    quality: '4K HDR',
    providers: ['Apple TV+']
  },
  {
    id: 103,
    title: 'Go Team!',
    media_type: 'movie',
    vote_average: 7.0,
    release_date: '2025',
    genres: ['Comedy', 'Sport'],
    overview: 'An eccentric office ensemble bands together for an unconventional championship tournament.',
    poster_path: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'LEjhY15eCx0',
    quality: 'HD',
    providers: ['Netflix']
  },
  {
    id: 104,
    title: 'Obsession',
    media_type: 'movie',
    vote_average: 7.5,
    release_date: '2024',
    genres: ['Mystery', 'Thriller', 'Drama'],
    overview: 'A deep psychological cat-and-mouse game through shadows and digital deception.',
    poster_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'Way9Dexny3w',
    quality: '4K HDR',
    providers: ['HBO Max']
  },
  {
    id: 105,
    title: 'Drawn Together',
    media_type: 'movie',
    vote_average: 7.9,
    release_date: '2025',
    genres: ['Romance', 'Drama'],
    overview: 'Two strangers discover their destinies intertwined against the backdrop of Manhattan.',
    poster_path: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'uYPbbksJxIg',
    quality: '4K HDR',
    providers: ['Hulu']
  },
  {
    id: 106,
    title: 'One Night Only',
    media_type: 'movie',
    vote_average: 7.3,
    release_date: '2024',
    genres: ['Music', 'Drama', 'Comedy'],
    overview: 'A dazzling night in the city where everything hangs in the balance for one magical performance.',
    poster_path: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'giXco2JaZ_4',
    quality: '4K HDR',
    providers: ['Netflix']
  },
  {
    id: 107,
    title: 'Practical Magic',
    media_type: 'movie',
    vote_average: 7.6,
    release_date: '2024',
    genres: ['Fantasy', 'Comedy', 'Romance'],
    overview: 'Two sisters born into a magical legacy unravel ancient curses and forbidden enchantments.',
    poster_path: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400&auto=format&fit=crop&q=80',
    backdrop_path: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1200&auto=format&fit=crop&q=80',
    youtube_id: 'd9MyW72ELq0',
    quality: '4K HDR',
    providers: ['HBO Max']
  }
];

export const TRENDING_SERIES: MediaItem[] = [
  {
    id: 30984,
    name: 'Bleach: Thousand-Year Blood War',
    title: 'Bleach: Thousand-Year Blood War',
    media_type: 'tv',
    vote_average: 8.8,
    first_air_date: '2022',
    genres: ['Animation', 'Action & Adventure', 'Sci-Fi & Fantasy'],
    overview: 'The peace is suddenly broken when warning sirens echo through the Soul Society.',
    poster_path: 'https://image.tmdb.org/t/p/w342/2EewFaXPsm277bgFsF7ioMC6vt5.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/70y1w6K89V2U9h0u2Y7R6v7k8j.jpg',
    youtube_id: 'e8YBesRKq_U',
    quality: '4K HDR',
    providers: ['Disney Plus', 'Hulu']
  },
  {
    id: 108978,
    name: 'Reacher',
    title: 'Reacher',
    media_type: 'tv',
    vote_average: 8.1,
    first_air_date: '2022',
    genres: ['Action & Adventure', 'Crime', 'Drama'],
    overview: 'Jack Reacher travels across America solving high-stakes conspiracies with brute intellect.',
    poster_path: 'https://image.tmdb.org/t/p/w342/j73SrPnljFarECRA2NvaoxBpLVl.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg',
    youtube_id: 'GSycMV_mptc',
    quality: '4K HDR',
    providers: ['Amazon Prime Video']
  },
  {
    id: 94605,
    name: 'Arcane',
    title: 'Arcane',
    media_type: 'tv',
    vote_average: 8.7,
    first_air_date: '2021',
    genres: ['Animation', 'Sci-Fi & Fantasy', 'Action & Adventure'],
    overview: 'Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows two iconic League champions.',
    poster_path: 'https://image.tmdb.org/t/p/w342/fqldfqMS6tMkE6320YUR50Y9Bql.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/v9acaWVxduaie2w44q5Ao7r9f4J.jpg',
    youtube_id: 'fXmAurh012s',
    quality: '4K HDR',
    providers: ['Netflix']
  },
  {
    id: 66732,
    name: 'Stranger Things',
    title: 'Stranger Things',
    media_type: 'tv',
    vote_average: 8.6,
    first_air_date: '2016',
    genres: ['Sci-Fi & Fantasy', 'Drama', 'Mystery'],
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.',
    poster_path: 'https://image.tmdb.org/t/p/w342/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    youtube_id: 'b9EkMc79ZSU',
    quality: '4K HDR',
    providers: ['Netflix']
  },
  {
    id: 126308,
    name: 'Shōgun',
    title: 'Shōgun',
    media_type: 'tv',
    vote_average: 8.5,
    first_air_date: '2024',
    genres: ['Drama', 'War & Politics'],
    overview: 'In 1600 Japan, Lord Yoshii Toranaga fights for his life as his enemies on the Council of Regents unite against him.',
    poster_path: 'https://image.tmdb.org/t/p/w342/7O4iVfOMQmdCSPxSw1Pj8WNVj9Q.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/zW0v2YT74C69cuiefl8vmvTneQ6.jpg',
    youtube_id: 'yAN5uspAoVE',
    quality: '4K HDR',
    providers: ['Hulu', 'Disney Plus']
  },
  {
    id: 100088,
    name: 'The Last of Us',
    title: 'The Last of Us',
    media_type: 'tv',
    vote_average: 8.6,
    first_air_date: '2023',
    genres: ['Drama', 'Sci-Fi & Fantasy'],
    overview: '20 years after modern civilization has been destroyed, Joel is hired to smuggle Ellie out of an oppressive quarantine zone.',
    poster_path: 'https://image.tmdb.org/t/p/w342/uKvVjK1qBtQm0Ap3U69xX4tU8yH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    youtube_id: 'uLtkt8BonwM',
    quality: '4K HDR',
    providers: ['HBO Max']
  },
  {
    id: 37854,
    name: 'One Piece',
    title: 'One Piece',
    media_type: 'tv',
    vote_average: 8.9,
    first_air_date: '1999',
    genres: ['Animation', 'Action & Adventure', 'Comedy'],
    overview: 'Monkey D. Luffy sets sail with his crew to find the legendary One Piece treasure.',
    poster_path: 'https://image.tmdb.org/t/p/w342/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/4Mt7iqKV22lHh8iFqV9q8b8e0.jpg',
    youtube_id: 'ln400c9hGVs',
    quality: 'HD',
    providers: ['Crunchyroll', 'Netflix']
  },
  {
    id: 93405,
    name: 'Squid Game',
    title: 'Squid Game',
    media_type: 'tv',
    vote_average: 7.8,
    first_air_date: '2021',
    genres: ['Action & Adventure', 'Mystery', 'Drama'],
    overview: 'Hundreds of cash-strapped players accept a strange invitation to compete in children’s games for a tempting prize.',
    poster_path: 'https://image.tmdb.org/t/p/w342/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    youtube_id: 'oqxAJKy0ii4',
    quality: '4K HDR',
    providers: ['Netflix']
  }
];

export const BECAUSE_YOU_WATCHED_ODYSSEY: MediaItem[] = [
  {
    id: 157336,
    title: 'Interstellar',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '2014',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
    poster_path: 'https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/rAiYTsqAlzk0vLbvoxDhqMwAbIQ.jpg',
    youtube_id: 'zSWdZVtXT7E',
    quality: '4K HDR',
    providers: ['Amazon Prime Video', 'Paramount Plus']
  },
  {
    id: 27205,
    title: 'Inception',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '2010',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    overview: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
    poster_path: 'https://image.tmdb.org/t/p/w342/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    youtube_id: 'YoHD9XEInc0',
    quality: '4K HDR',
    providers: ['HBO Max']
  },
  {
    id: 155,
    title: 'The Dark Knight',
    media_type: 'movie',
    vote_average: 8.5,
    release_date: '2008',
    genres: ['Drama', 'Action', 'Crime', 'Thriller'],
    overview: 'Batman raises the stakes in his war on crime with the help of Lt. Jim Gordon and District Attorney Harvey Dent.',
    poster_path: 'https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    youtube_id: 'EXeTwQWrcwY',
    quality: '4K HDR',
    providers: ['HBO Max']
  },
  {
    id: 361743,
    title: 'Top Gun: Maverick',
    media_type: 'movie',
    vote_average: 8.2,
    release_date: '2022',
    genres: ['Action', 'Drama'],
    overview: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator training a detachment of graduates.',
    poster_path: 'https://image.tmdb.org/t/p/w342/62HCnUTziyWcpDaBO2i1DX17pmH.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    youtube_id: 'giXco2JaZ_4',
    quality: '4K HDR',
    providers: ['Paramount Plus']
  },
  {
    id: 603692,
    title: 'John Wick: Chapter 4',
    media_type: 'movie',
    vote_average: 7.7,
    release_date: '2023',
    genres: ['Action', 'Thriller', 'Crime'],
    overview: 'John Wick uncovers a path to defeating The High Table, but must face a new enemy with powerful alliances.',
    poster_path: 'https://image.tmdb.org/t/p/w342/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/7I6VUdPj6tQECNHdviJkUHD2389.jpg',
    youtube_id: 'qEVUtrk8_B4',
    quality: '4K HDR',
    providers: ['Starz']
  },
  {
    id: 98,
    title: 'Gladiator',
    media_type: 'movie',
    vote_average: 8.2,
    release_date: '2000',
    genres: ['Action', 'Drama', 'Adventure'],
    overview: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
    poster_path: 'https://image.tmdb.org/t/p/w342/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/kXfqXt22df3MFdfrmb25Urz7xUh.jpg',
    youtube_id: 'owK1qxDselE',
    quality: '4K HDR',
    providers: ['Paramount Plus', 'Amazon Prime Video']
  }
];

export const NETFLIX_MOVIES: MediaItem[] = [
  {
    id: 315635,
    title: 'Spider-Man: Homecoming',
    media_type: 'movie',
    vote_average: 7.4,
    release_date: '2017',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    overview: 'Peter Parker balances his life as an ordinary high school student while moonlighting as the superhero Spider-Man.',
    poster_path: 'https://image.tmdb.org/t/p/w342/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/fn4n6uOYcB6Uh89nbNzyjg2h9Q5.jpg',
    youtube_id: 'n9DwoQ7HWvI',
    quality: '4K HDR',
    providers: ['Netflix', 'Disney Plus']
  },
  {
    id: 64690,
    title: 'Drive',
    media_type: 'movie',
    vote_average: 7.9,
    release_date: '2011',
    genres: ['Drama', 'Thriller', 'Crime'],
    overview: 'A mysterious Hollywood action film stuntman and getaway driver gets into trouble when he helps out his neighbor.',
    poster_path: 'https://image.tmdb.org/t/p/w342/da0o30os116t8jBq44I6lJ47eR6.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/3V4kSt3k0A9n2w0uN9vV9kG2r4e.jpg',
    youtube_id: 'KBiOF3y1W0Y',
    quality: 'HD',
    providers: ['Netflix']
  },
  {
    id: 399566,
    title: 'Godzilla vs. Kong',
    media_type: 'movie',
    vote_average: 7.6,
    release_date: '2021',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    overview: 'In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course.',
    poster_path: 'https://image.tmdb.org/t/p/w342/pgqgaUx1cJb5oZQQ5v0t9R8xW0.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/inJjDhCjfhh3RtrJWBmmDqeuSYC.jpg',
    youtube_id: 'odM92ap8_c0',
    quality: '4K HDR',
    providers: ['Netflix']
  },
  {
    id: 496243,
    title: 'Parasite',
    media_type: 'movie',
    vote_average: 8.5,
    release_date: '2019',
    genres: ['Comedy', 'Thriller', 'Drama'],
    overview: 'All unemployed, Ki-taek’s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood.',
    poster_path: 'https://image.tmdb.org/t/p/w342/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/hiKmpZMGZsrkA3cdEv9a7Y7QngC.jpg',
    youtube_id: '5xH0RZE76iM',
    quality: '4K HDR',
    providers: ['Netflix', 'Hulu']
  },
  {
    id: 550,
    title: 'Fight Club',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '1999',
    genres: ['Drama'],
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    poster_path: 'https://image.tmdb.org/t/p/w342/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    youtube_id: 'qtRKDV93JU8',
    quality: 'HD',
    providers: ['Netflix']
  },
  {
    id: 603,
    title: 'The Matrix',
    media_type: 'movie',
    vote_average: 8.2,
    release_date: '1999',
    genres: ['Action', 'Sci-Fi'],
    overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster_path: 'https://image.tmdb.org/t/p/w342/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/7c4t5y6u7i8o9p0a1b2c3d4e.jpg',
    youtube_id: 'vKQi3bBA1y8',
    quality: '4K HDR',
    providers: ['Netflix', 'HBO Max']
  }
];

export const NETFLIX_SERIES: MediaItem[] = [
  {
    id: 1396,
    name: 'Breaking Bad',
    title: 'Breaking Bad',
    media_type: 'tv',
    vote_average: 9.5,
    first_air_date: '2008',
    genres: ['Drama', 'Crime', 'Thriller'],
    overview: 'A chemistry teacher diagnosed with terminal lung cancer turns to manufacturing methamphetamine.',
    poster_path: 'https://image.tmdb.org/t/p/w342/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    youtube_id: 'HhesaQXLuRY',
    number_of_seasons: 5,
    quality: '4K HDR',
    providers: ['Netflix']
  },
  {
    id: 1416,
    name: "Grey's Anatomy",
    title: "Grey's Anatomy",
    media_type: 'tv',
    vote_average: 8.2,
    first_air_date: '2005',
    genres: ['Drama', 'Romance'],
    overview: 'Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.',
    poster_path: 'https://image.tmdb.org/t/p/w342/clnyhPqj1SNgpYWziZysSJNp9nM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/7c4t5y6u7i8o9p0a1b2c3d4e.jpg',
    youtube_id: 'd96cjJhvlMA',
    number_of_seasons: 20,
    quality: 'HD',
    providers: ['Netflix', 'Hulu']
  },
  {
    id: 34307,
    name: 'Shameless',
    title: 'Shameless',
    media_type: 'tv',
    vote_average: 8.2,
    first_air_date: '2011',
    genres: ['Drama', 'Comedy'],
    overview: 'A fiercely dysfunctional Chicago family survives with grit, humor, and rebellious resilience.',
    poster_path: 'https://image.tmdb.org/t/p/w342/9akij7PqZ1gNxVsZ79mAMLQZ9PP.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/8s9t0u1v2w3x4y5z6a7b8c9d.jpg',
    youtube_id: '7mR2uM_y6m0',
    number_of_seasons: 11,
    quality: 'HD',
    providers: ['Netflix']
  },
  {
    id: 85271,
    name: 'WandaVision',
    title: 'WandaVision',
    media_type: 'tv',
    vote_average: 8.2,
    first_air_date: '2021',
    genres: ['Sci-Fi & Fantasy', 'Mystery', 'Drama'],
    overview: 'Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.',
    poster_path: 'https://image.tmdb.org/t/p/w342/glKDDbSkyP49hdRIgl3ZG99AMa5.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/14QbnygCuTO0vl7bY090L7Y33nk.jpg',
    youtube_id: 'UBhlqe2KVt4',
    number_of_seasons: 1,
    quality: '4K HDR',
    providers: ['Disney Plus']
  },
  {
    id: 60625,
    name: 'Rick and Morty',
    title: 'Rick and Morty',
    media_type: 'tv',
    vote_average: 8.7,
    first_air_date: '2013',
    genres: ['Animation', 'Comedy', 'Sci-Fi & Fantasy'],
    overview: 'An eccentric, sociopathic scientist drags his timid grandson on insane cross-dimensional adventures.',
    poster_path: 'https://image.tmdb.org/t/p/w342/gdIrmFD892Pp4528Df0ddef9v9v.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/70y1w6K89V2U9h0u2Y7R6v7k8j.jpg',
    youtube_id: 'hl1U0bxTHbY',
    number_of_seasons: 7,
    quality: '4K HDR',
    providers: ['Netflix', 'HBO Max']
  }
];

export const BASED_ON_TRUE_STORY: MediaItem[] = [
  {
    id: 598,
    title: 'City of God',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '2002',
    genres: ['Drama', 'Crime'],
    overview: 'In the slums of Rio, two kids’ paths diverge: one strives to become a photographer, the other a kingpin.',
    poster_path: 'https://image.tmdb.org/t/p/w342/k7eYdWvhYQZRFdoQb590AcRdCeT.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/k7eYdWvhYQZRFdoQb590AcRdCeT.jpg',
    youtube_id: 'dcUOO4Itgmw',
    quality: 'HD',
    providers: ['Apple TV+', 'Amazon Prime Video']
  },
  {
    id: 423,
    title: 'The Pianist',
    media_type: 'movie',
    vote_average: 8.4,
    release_date: '2002',
    genres: ['Drama', 'War', 'Biography'],
    overview: 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
    poster_path: 'https://image.tmdb.org/t/p/w342/2hFvxCCWrTmCYw2etEpLDmqaEtM.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/2hFvxCCWrTmCYw2etEpLDmqaEtM.jpg',
    youtube_id: 'BFwGqLa_oAo',
    quality: 'HD',
    providers: ['Starz', 'Amazon Prime Video']
  },
  {
    id: 7345,
    title: 'There Will Be Blood',
    media_type: 'movie',
    vote_average: 8.1,
    release_date: '2007',
    genres: ['Drama'],
    overview: 'A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.',
    poster_path: 'https://image.tmdb.org/t/p/w342/fa0RDkAlCec0STnT7dFcNyDu9vj.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/fa0RDkAlCec0STnT7dFcNyDu9vj.jpg',
    youtube_id: 'FeSLPELpMeM',
    quality: '4K HDR',
    providers: ['Paramount Plus']
  },
  {
    id: 238,
    title: 'The Godfather',
    media_type: 'movie',
    vote_average: 8.7,
    release_date: '1972',
    genres: ['Drama', 'Crime'],
    overview: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    poster_path: 'https://image.tmdb.org/t/p/w342/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/tmU7aVZLiVJt9vRGlM726iKyhoW.jpg',
    youtube_id: 'sY1S34973zA',
    quality: '4K HDR',
    providers: ['Paramount Plus']
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    media_type: 'movie',
    vote_average: 8.5,
    release_date: '1994',
    genres: ['Crime', 'Thriller'],
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster_path: 'https://image.tmdb.org/t/p/w342/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    youtube_id: 's7EdQ4FqbhY',
    quality: '4K HDR',
    providers: ['HBO Max']
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    media_type: 'movie',
    vote_average: 8.7,
    release_date: '1994',
    genres: ['Drama', 'Crime'],
    overview: 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
    poster_path: 'https://image.tmdb.org/t/p/w342/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    backdrop_path: 'https://image.tmdb.org/t/p/w780/kXfqXt22df3MFdfrmb25Urz7xUh.jpg',
    youtube_id: 'PLl99DlL6b4',
    quality: '4K HDR',
    providers: ['HBO Max']
  }
];

export const ALL_MEDIA_CATALOG: MediaItem[] = [
  ...HERO_FEATURED_ITEMS,
  ...TRENDING_MOVIES,
  ...TRENDING_SERIES,
  ...BECAUSE_YOU_WATCHED_ODYSSEY,
  ...NETFLIX_MOVIES,
  ...NETFLIX_SERIES,
  ...BASED_ON_TRUE_STORY
].filter((item, index, self) => index === self.findIndex((t) => t.id === item.id));
